version: '3.8'
services:
  backend:
    build:
      context: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
    restart: always
    environment:
      HOST: 0.0.0.0
    env_file: ./api/.env
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app